package com.alibaba.webx.common.po.financial;

import com.alibaba.webx.common.po.financial.Rate;

public interface RateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    int insert(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    int insertSelective(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    Rate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    int updateByPrimaryKeySelective(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Mon Nov 28 22:20:47 CST 2016
     */
    int updateByPrimaryKey(Rate record);
}